package exam;

import java.sql.SQLException;

import exceptions.InvalidCityException;
import exceptions.InvalidNameExeption;
import exceptions.InvalidPersonalNumberException;

public class Demo {

	public static void main(String[] args) throws SQLException, InvalidNameExeption, InvalidCityException, InvalidPersonalNumberException {
		
		TestDbConnection test = new TestDbConnection();
		
		Person rabotnik = new Person("Stamat Ivanov Stamatov", "0885858585" , City.Sofia, "778587777"){};
		Person rabotnik2 = new Person("Vasil Gocev Stoev", "0599558787" , City.Varna, "84858489"){};
		Person rabotnik3 = new Person("Stamat Ivanov Stamatov", "0477878789" , City.Veliko_Tarnovo, "121113158"){};
		Person rabotnik4 = new Person("Stamat Ivanov Stamatov", "998877665544" , City.Ruse, "311112545"){};
		test.addEmployee(rabotnik);
		test.addEmployee(rabotnik2);
		test.addEmployee(rabotnik3);
		test.addEmployee(rabotnik4);
		
		test.getEmployee("Alex");
	}

}
